export const countries : {[key: string]: {code: string, currency: string}} = {
  
  "Afghanistan": {"code": "AF", "currency": "AFN"},
  "Albania": {"code": "AL", "currency": "ALL"},
  "Algeria": {"code": "DZ", "currency": "DZD"},
  "Andorra": {"code": "AD", "currency": "EUR"},
  "Angola": {"code": "AO", "currency": "AOA"},
  "Antigua and Barbuda": {"code": "AG", "currency": "XCD"},
  "Argentina": {"code": "AR", "currency": "ARS"},
  "Armenia": {"code": "AM", "currency": "AMD"},
  "Australia": {"code": "AU", "currency": "AUD"},
  "Austria": {"code": "AT", "currency": "EUR"},
  "Azerbaijan": {"code": "AZ", "currency": "AZN"},
  "Bahamas": {"code": "BS", "currency": "BSD"},
  "Bahrain": {"code": "BH", "currency": "BHD"},
  "Bangladesh": {"code": "BD", "currency": "BDT"},
  "Barbados": {"code": "BB", "currency": "BBD"},
  "Belarus": {"code": "BY", "currency": "BYN"},
  "Belgium": {"code": "BE", "currency": "EUR"},
  "Belize": {"code": "BZ", "currency": "BZD"},
  "Benin": {"code": "BJ", "currency": "XOF"},
  "Bhutan": {"code": "BT", "currency": "BTN"},
  "Bolivia": {"code": "BO", "currency": "BOB"},
  "Bosnia and Herzegovina": {"code": "BA", "currency": "BAM"},
  "Botswana": {"code": "BW", "currency": "BWP"},
  "Brazil": {"code": "BR", "currency": "BRL"},
  "Brunei": {"code": "BN", "currency": "BND"},
  "Bulgaria": {"code": "BG", "currency": "BGN"},
  "Burkina Faso": {"code": "BF", "currency": "XOF"},
  "Burundi": {"code": "BI", "currency": "BIF"},
  "Cabo Verde": {"code": "CV", "currency": "CVE"},
  "Cambodia": {"code": "KH", "currency": "KHR"},
  "Cameroon": {"code": "CM", "currency": "XAF"},
  "Canada": {"code": "CA", "currency": "CAD"},
  "Central African Republic": {"code": "CF", "currency": "XAF"},
  "Chad": {"code": "TD", "currency": "XAF"},
  "Chile": {"code": "CL", "currency": "CLP"},
  "China": {"code": "CN", "currency": "CNY"},
  "Colombia": {"code": "CO", "currency": "COP"},
  "Comoros": {"code": "KM", "currency": "KMF"},
  "Congo (Congo-Brazzaville)": {"code": "CG", "currency": "CDF"},
  "Costa Rica": {"code": "CR", "currency": "CRC"},
  "Croatia": {"code": "HR", "currency": "HRK"},
  "Cuba": {"code": "CU", "currency": "CUP"},
  "Cyprus": {"code": "CY", "currency": "EUR"},
  "Czechia (Czech Republic)": {"code": "CZ", "currency": "CZK"},
  "Denmark": {"code": "DK", "currency": "DKK"},
  "Djibouti": {"code": "DJ", "currency": "DJF"},
  "Dominica": {"code": "DM", "currency": "XCD"},
  "Dominican Republic": {"code": "DO", "currency": "DOP"},
  "Ecuador": {"code": "EC", "currency": "USD"},
  "Egypt": {"code": "EG", "currency": "EGP"},
  "El Salvador": {"code": "SV", "currency": "USD"},
  "Equatorial Guinea": {"code": "GQ", "currency": "XAF"},
  "Eritrea": {"code": "ER", "currency": "ERN"},
  "Estonia": {"code": "EE", "currency": "EUR"},
  "Eswatini (fmr. Swaziland)": {"code": "SZ", "currency": "SZL"},
  "Ethiopia": {"code": "ET", "currency": "ETB"},
  "Fiji": {"code": "FJ", "currency": "FJD"},
  "Finland": {"code": "FI", "currency": "EUR"},
  "France": {"code": "FR", "currency": "EUR"},
  "Gabon": {"code": "GA", "currency": "XAF"},
  "Gambia": {"code": "GM", "currency": "GMD"},
  "Georgia": {"code": "GE", "currency": "GEL"},
  "Germany": {"code": "DE", "currency": "EUR"},
  "Ghana": {"code": "GH", "currency": "GHS"},
  "Greece": {"code": "GR", "currency": "EUR"},
  "Grenada": {"code": "GD", "currency": "XCD"},
  "Guatemala": {"code": "GT", "currency": "GTQ"},
  "Guinea": {"code": "GN", "currency": "GNF"},
  "Guinea-Bissau": {"code": "GW", "currency": "XOF"},
  "Guyana": {"code": "GY", "currency": "GYD"},
  "Haiti": {"code": "HT", "currency": "HTG"},
  "Honduras": {"code": "HN", "currency": "HNL"},
  "Hong Kong": {"code": "HK", "currency": "HKD"},
  "Hungary": {"code": "HU", "currency": "HUF"},
  "Iceland": {"code": "IS", "currency": "ISK"},
  "India": {"code": "IN", "currency": "INR"},
  "Indonesia": {"code": "ID", "currency": "IDR"},
  "Iran": {"code": "IR", "currency": "IRR"},
  "Iraq": {"code": "IQ", "currency": "IQD"},
  "Ireland": {"code": "IE", "currency": "EUR"},
  "Israel": {"code": "IL", "currency": "ILS"},
  "Italy": {"code": "IT", "currency": "EUR"},
  "Jamaica": {"code": "JM", "currency": "JMD"},
  "Japan": {"code": "JP", "currency": "JPY"},
  "Jordan": {"code": "JO", "currency": "JOD"},
  "Kazakhstan": {"code": "KZ", "currency": "KZT"},
  "Kenya": {"code": "KE", "currency": "KES"},
  "Kiribati": {"code": "KI", "currency": "AUD"},
  "Kuwait": {"code": "KW", "currency": "KWD"},
  "Kyrgyzstan": {"code": "KG", "currency": "KGS"},
  "Laos": {"code": "LA", "currency": "LAK"},
  "Latvia": {"code": "LV", "currency": "EUR"},
  "Lebanon": {"code": "LB", "currency": "LBP"},
  "Lesotho": {"code": "LS", "currency": "LSL"},
  "Liberia": {"code": "LR", "currency": "LRD"},
  "Libya": {"code": "LY", "currency": "LYD"},
  "Liechtenstein": {"code": "LI", "currency": "CHF"},
  "Lithuania": {"code": "LT", "currency": "EUR"},
  "Luxembourg": {"code": "LU", "currency": "EUR"},
  "Madagascar": {"code": "MG", "currency": "MGA"},
  "Malawi": {"code": "MW", "currency": "MWK"},
  "Malaysia": {"code": "MY", "currency": "MYR"},
  "Maldives": {"code": "MV", "currency": "MVR"},
  "Mali": {"code": "ML", "currency": "XOF"},
  "Malta": {"code": "MT", "currency": "EUR"},
  "Marshall Islands": {"code": "MH", "currency": "USD"},
  "Mauritania": {"code": "MR", "currency": "MRU"},
  "Mauritius": {"code": "MU", "currency": "MUR"},
  "Mexico": {"code": "MX", "currency": "MXN"},
  "Micronesia": {"code": "FM", "currency": "USD"},
  "Moldova": {"code": "MD", "currency": "MDL"},
  "Monaco": {"code": "MC", "currency": "EUR"},
  "Mongolia": {"code": "MN", "currency": "MNT"},
  "Montenegro": {"code": "ME", "currency": "EUR"},
  "Morocco": {"code": "MA", "currency": "MAD"},
  "Mozambique": {"code": "MZ", "currency": "MZN"},
  "Myanmar (formerly Burma)": {"code": "MM", "currency": "MMK"},
  "Namibia": {"code": "NA", "currency": "NAD"},
  "Nauru": {"code": "NR", "currency": "AUD"},
  "Nepal": {"code": "NP", "currency": "NPR"},
  "Netherlands": {"code": "NL", "currency": "EUR"},
  "New Zealand": {"code": "NZ", "currency": "NZD"},
  "Nicaragua": {"code": "NI", "currency": "NIO"},
  "Niger": {"code": "NE", "currency": "XOF"},
  "Nigeria": {"code": "NG", "currency": "NGN"},
  "North Korea": {"code": "KP", "currency": "KPW"},
  "North Macedonia": {"code": "MK", "currency": "MKD"},
  "Norway": {"code": "NO", "currency": "NOK"},
  "Oman": {"code": "OM", "currency": "OMR"},
  "Pakistan": {"code": "PK", "currency": "PKR"},
  "Palau": {"code": "PW", "currency": "USD"},
  "Palestine State": {"code": "PS", "currency": "ILS"},
  "Panama": {"code": "PA", "currency": "PAB"},
  "Papua New Guinea": {"code": "PG", "currency": "PGK"},
  "Paraguay": {"code": "PY", "currency": "PYG"},
  "Peru": {"code": "PE", "currency": "PEN"},
  "Philippines": {"code": "PH", "currency": "PHP"},
  "Poland": {"code": "PL", "currency": "PLN"},
  "Portugal": {"code": "PT", "currency": "EUR"},
  "Qatar": {"code": "QA", "currency": "QAR"},
  "Romania": {"code": "RO", "currency": "RON"},
  "Russia": {"code": "RU", "currency": "RUB"},
  "Rwanda": {"code": "RW", "currency": "RWF"},
  "Saint Kitts and Nevis": {"code": "KN", "currency": "XCD"},
  "Saint Lucia": {"code": "LC", "currency": "XCD"},
  "Saint Vincent and the Grenadines": {"code": "VC", "currency": "XCD"},
  "Samoa": {"code": "WS", "currency": "WST"},
  "San Marino": {"code": "SM", "currency": "EUR"},
  "Sao Tome and Principe": {"code": "ST", "currency": "STN"},
  "Saudi Arabia": {"code": "SA", "currency": "SAR"},
  "Senegal": {"code": "SN", "currency": "XOF"},
  "Serbia": {"code": "RS", "currency": "RSD"},
  "Seychelles": {"code": "SC", "currency": "SCR"},
  "Sierra Leone": {"code": "SL", "currency": "SLL"},
  "Singapore": {"code": "SG", "currency": "SGD"},
  "Slovakia": {"code": "SK", "currency": "EUR"},
  "Slovenia": {"code": "SI", "currency": "EUR"},
  "Solomon Islands": {"code": "SB", "currency": "SBD"},
  "Somalia": {"code": "SO", "currency": "SOS"},
  "South Africa": {"code": "ZA", "currency": "ZAR"},
  "South Korea": {"code": "KR", "currency": "KRW"},
  "South Sudan": {"code": "SS", "currency": "SSP"},
  "Spain": {"code": "ES", "currency": "EUR"},
  "Sri Lanka": {"code": "LK", "currency": "LKR"},
  "Sudan": {"code": "SD", "currency": "SDG"},
  "Suriname": {"code": "SR", "currency": "SRD"},
  "Sweden": {"code": "SE", "currency": "SEK"},
  "Switzerland": {"code": "CH", "currency": "CHF"},
  "Syria": {"code": "SY", "currency": "SYP"},
  "Taiwan": {"code": "TW", "currency": "TWD"},
  "Tajikistan": {"code": "TJ", "currency": "TJS"},
  "Tanzania": {"code": "TZ", "currency": "TZS"},
  "Thailand": {"code": "TH", "currency": "THB"},
  "Timor-Leste": {"code": "TL", "currency": "USD"},
  "Togo": {"code": "TG", "currency": "XOF"},
  "Tonga": {"code": "TO", "currency": "TOP"},
  "Trinidad and Tobago": {"code": "TT", "currency": "TTD"},
  "Tunisia": {"code": "TN", "currency": "TND"},
  "Turkey": {"code": "TR", "currency": "TRY"},
  "Turkmenistan": {"code": "TM", "currency": "TMT"},
  "Tuvalu": {"code": "TV", "currency": "AUD"},
  "Uganda": {"code": "UG", "currency": "UGX"},
  "Ukraine": {"code": "UA", "currency": "UAH"},
  "United Arab Emirates": {"code": "AE", "currency": "AED"},
  "United Kingdom": {"code": "GB", "currency": "GBP"},
  "United States": {"code": "US", "currency": "USD"},
  "Uruguay": {"code": "UY", "currency": "UYU"},
  "Uzbekistan": {"code": "UZ", "currency": "UZS"},
  "Vanuatu": {"code": "VU", "currency": "VUV"},
  "Venezuela": {"code": "VE", "currency": "VES"},
  "Vietnam": {"code": "VN", "currency": "VND"},
  "Yemen": {"code": "YE", "currency": "YER"},
  "Zambia": {"code": "ZM", "currency": "ZMW"},
  "Zimbabwe": {"code": "ZW", "currency": "ZWL"}
}

export default countries