export const citiesByContinent: { [key: string]: { city: string, country: string }[] } = {
  Asia: [
    { city: 'Hong Kong', country: 'China' },
    { city: 'Osaka', country: 'Japan' },
    { city: 'Shanghai', country: 'China' },
    { city: 'Taipei', country: 'Taiwan' },
    { city: 'Tokyo', country: 'Japan' },
    { city: 'Seoul', country: 'South Korea' }
  ],
  Europe: [
    { city: 'Berlin', country: 'Germany' },
    { city: 'London', country: 'United Kingdom' },
    { city: 'Madrid', country: 'Spain' },
    { city: 'Paris', country: 'France' },
    { city: 'Rome', country: 'Italy' }
  ],
  "North America": [
    { city: 'Los Angeles', country: 'United States' },
    { city: 'Miami', country: 'United States' },
    { city: 'San Francisco', country: 'United States' },
    { city: 'Toronto', country: 'Canada' },
    { city: 'Vancouver', country: 'Canada' }
  ],
  Australia: [
    { city: 'Brisbane', country: 'Australia' },
    { city: 'Melbourne', country: 'Australia' },
    { city: 'Sydney', country: 'Australia' }
  ]
};

export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antigua & Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Ascension',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Azores',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia-Herzegovina',
  'Botswana',
  'Brazil',
  'British Virgin Islands',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burma',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Corsica',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'Gabon',
  'Gambia',
  'Republic of Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'North Korea',
  'South Korea',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Republic of Macedonia',
  'Madagascar',
  'Madeira Islands',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Republic of Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Federated States of Micronesia, Federated States of',
  'Moldova',
  'Mongolia',
  'Montenegro (Serbia-Montenegro)',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcaim Islands',
  'Poland',
  'Portugal',
  'Qatar',
  'Reunion',
  'Romania',
  'Russia',
  'Rwanda',
  'St. Christopher (St. Kitts) & Nevis',
  'St. Helena',
  'St. Lucia',
  'St. Pierre & Miquelon',
  'St. Vincent & the Grenadines',
  'San Marino',
  'Santa Cruz Islands',
  'Sao Tome & Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia-Montenegro (Yugoslavia)',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovak Republic (Slovakia)',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Tahiti',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad & Tobago',
  'Tristan da Cunha',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks & Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Virgin Islands',
  'Wallis & Futuna Islands',
  'Western Samoa',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];
